---
- name: restart apache
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_facts['distribution'] == "Amazon"

- name: restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
  when: ansible_facts['distribution'] == "Amazon"
